"""Add unique constraint on vehicle_id and order_id

Revision ID: c28cae18ca61
Revises: f8a2464c1ce2
Create Date: 2025-04-06 15:02:08.537277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28cae18ca61'
down_revision: Union[str, None] = 'f8a2464c1ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_vehicle_order', 'tripsheets', ['vehicle_id', 'order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_vehicle_order', 'tripsheets', type_='unique')
    # ### end Alembic commands ###
